"""empty message

Revision ID: 2895a31f1518
Revises: 6d715a62292b
Create Date: 2019-04-18 09:37:03.987721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2895a31f1518'
down_revision = '6d715a62292b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'organ', ['name'])
    op.add_column('slice', sa.Column('objective', sa.String(length=200), nullable=True))
    op.drop_column('slice', 'resolution')
    op.drop_column('slice', 'sample_number')
    op.drop_column('slice', 'survey_classification')
    op.drop_column('slice', 'probe_id')
    op.drop_column('slice', 'location_index')
    op.drop_column('slice', 'z_step_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slice', sa.Column('z_step_size', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('slice', sa.Column('location_index', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('slice', sa.Column('probe_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('slice', sa.Column('survey_classification', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('slice', sa.Column('sample_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('slice', sa.Column('resolution', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('slice', 'objective')
    op.drop_constraint(None, 'organ', type_='unique')
    # ### end Alembic commands ###
