"""empty message

Revision ID: 6bf9dd1519ef
Revises: 
Create Date: 2019-05-13 11:41:57.504011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf9dd1519ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('gene', sa.Column('gene_name_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'gene', 'gene_name', ['gene_name_id'], ['id'])
    op.drop_column('gene', 'name')
    op.add_column('lookup', sa.Column('gene_name_id', sa.Integer(), nullable=False))
    op.drop_constraint('lookup_gene_id_fkey', 'lookup', type_='foreignkey')
    op.create_foreign_key(None, 'lookup', 'gene_name', ['gene_name_id'], ['id'])
    op.drop_column('lookup', 'gene_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lookup', sa.Column('gene_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lookup', type_='foreignkey')
    op.create_foreign_key('lookup_gene_id_fkey', 'lookup', 'gene', ['gene_id'], ['id'])
    op.drop_column('lookup', 'gene_name_id')
    op.add_column('gene', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gene', type_='foreignkey')
    op.drop_column('gene', 'gene_name_id')
    op.drop_table('gene_name')
    # ### end Alembic commands ###
