"""empty message

Revision ID: 95ff6c56d8fa
Revises: cdfe7b43005c
Create Date: 2018-12-05 12:45:08.088228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ff6c56d8fa'
down_revision = 'cdfe7b43005c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('img_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'img_path')
    # ### end Alembic commands ###
