"""empty message

Revision ID: a847a4afba9d
Revises: 
Create Date: 2018-12-12 13:53:52.379155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a847a4afba9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genotype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mani_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('genotype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genotype_id'], ['genotype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=200), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('mani_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], ),
    sa.ForeignKeyConstraint(['mani_type_id'], ['mani_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('slice_id', sa.Integer(), nullable=True),
    sa.Column('location_index', sa.String(length=200), nullable=True),
    sa.Column('resolution', sa.String(length=200), nullable=True),
    sa.Column('instrument', sa.String(length=200), nullable=True),
    sa.Column('wavelength', sa.Integer(), nullable=True),
    sa.Column('probe_id', sa.String(length=200), nullable=True),
    sa.Column('survey_classification', sa.String(length=200), nullable=True),
    sa.Column('checksum', sa.String(length=200), nullable=True),
    sa.Column('img_path', sa.String(length=500), nullable=True),
    sa.Column('organ_id', sa.Integer(), nullable=False),
    sa.Column('mouse_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('combined_data', sa.String(length=800), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['mouse_id'], ['mouse.id'], ),
    sa.ForeignKeyConstraint(['organ_id'], ['organ.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('combined_data')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slice')
    op.drop_table('mouse')
    op.drop_table('gene')
    op.drop_table('organ')
    op.drop_table('mani_type')
    op.drop_table('genotype')
    op.drop_table('experiment')
    # ### end Alembic commands ###
