"""empty message

Revision ID: b44bc019ad13
Revises: 6bf9dd1519ef
Create Date: 2019-05-13 12:52:59.739096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44bc019ad13'
down_revision = '6bf9dd1519ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slice', sa.Column('z_step_size', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slice', 'z_step_size')
    # ### end Alembic commands ###
