"""empty message

Revision ID: cdfe7b43005c
Revises: 
Create Date: 2018-12-05 12:40:01.247358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfe7b43005c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zinc_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('symbol', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('organ',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_date'), 'scan', ['date'], unique=False)
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('gene_id', sa.Integer(), nullable=True),
    sa.Column('cmpd_id', sa.Integer(), nullable=True),
    sa.Column('organ_id', sa.Integer(), nullable=True),
    sa.Column('op_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Interval(), nullable=True),
    sa.Column('scan_id', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['cmpd_id'], ['compound.id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], ),
    sa.ForeignKeyConstraint(['op_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['organ_id'], ['organ.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_date'), 'dataset', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_date'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_scan_date'), table_name='scan')
    op.drop_table('scan')
    op.drop_table('sample')
    op.drop_table('organ')
    op.drop_table('operator')
    op.drop_table('gene')
    op.drop_table('compound')
    # ### end Alembic commands ###
