"""empty message

Revision ID: 28cf080d7315
Revises: 
Create Date: 2023-08-30 22:24:13.166563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cf080d7315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtype_name', sa.String(length=80), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['gene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gene', sa.Column('construct', sa.String(length=80), nullable=True))
    op.add_column('mouse', sa.Column('subtype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mouse', 'subtype', ['subtype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mouse', type_='foreignkey')
    op.drop_column('mouse', 'subtype_id')
    op.drop_column('gene', 'construct')
    op.drop_table('subtype')
    # ### end Alembic commands ###
